version: '3.8'
services:
  movies:
    image: sumith596/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: sumith596/paytrains:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: sumith596/paydth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: sumith596/payrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

